[package]
name = "syswall"
version = "0.1.0"
authors = ["Simon Pugnet <simon@polaris64.net>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
libc = "0.2.48"
log = "0.4.6"
nix = "0.13.0"
serde = { version = "1.0.87", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.1.8"
